import {onlineRequest} from './online-client.js';
import {paletteControl} from './palettes.js';
import {edgeStyle} from './edge-style.js';
function annotationEvidence(d){
  const evidence=d.evidence||[];
  return evidence.length?`<details class="evidence"><summary>人工 / 同源 / 其他物种注释原文（${evidence.length} 条）</summary><p class="note">按工作簿 ZLC ID 精确匹配；其他物种的名称及功能作为参考。多种人工名称均保留。</p>${evidence.map(e=>`<article><strong>${esc(e.sheet)} · 第 ${e.row} 行</strong><div class="note">${esc(e.kind)}</div><dl>${Object.entries(e.fields).map(([key,value])=>`<dt>${esc(key)}</dt><dd>${esc(value)}</dd>`).join('')}</dl></article>`).join('')}</details>`:'';
}
function styleEdges(){
  const options={positive:$('positiveColor').value,negative:$('negativeColor').value,variable:$('edgeWidth').value==='correlation'};
  document.querySelectorAll('#network line[data-pcc]').forEach(line=>{
    const s=edgeStyle(Number(line.dataset.pcc),options);
    line.setAttribute('stroke',s.color);line.setAttribute('stroke-width',s.width.toFixed(3));
    line.setAttribute('stroke-opacity',s.opacity.toFixed(3));line.setAttribute('stroke-dasharray',s.dash);
  });
  $('edgeLegend').innerHTML=`<span style="color:${options.positive}">━━ 正相关</span>　<span style="color:${options.negative}">┄┄ 负相关</span>　${options.variable?'|PCC| 0 → 1：线宽 0.7 → 5；相关越强越粗、越深':'固定线宽 1.5；相关越强越深'}（固定尺度，不随阈值重标定）`;
}
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current, page=1,result,detail,graph,graphParams,epoch=0,detailEpoch=0,tableEpoch=0;const cache=new Map();
async function api(route,p={}){return onlineRequest(route,p)}
function error(e){$('status').textContent=e.message;$('status').className='error'}
const guarded=f=>(...args)=>Promise.resolve().then(()=>f(...args)).catch(error);
const netParams=()=>({...current,limit:$('limit').value,depth:$('depth').value,cap:$('cap').value,inter:$('inter').checked});
async function download(format){if(!current)return;try{const d=await api('download',{...((format==='network'&&graphParams)?graphParams:current),format});const url=URL.createObjectURL(new Blob([d.text],{type:'text/tab-separated-values;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=d.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){error(e)}}
async function table(){if(!current)return;const version=epoch,request=++tableEpoch;const r=await api('query',{...current,page,search:$('search').value,sort:$('sort').value,order:$('order').value});if(version!==epoch||request!==tableEpoch)return;result=r;$('count').textContent=`${r.total.toLocaleString()} 个`;$('rows').innerHTML=r.rows.length?r.rows.map(x=>`<tr><td><button data-heat="${esc(x.id)}" aria-label="加入热图 ${esc(x.id)}">＋</button></td><td><button class="link" data-gene="${esc(x.id)}">${esc(x.id)}</button>${x.alias?`<div class="genealias">${esc(x.alias)}</div>`:''}</td><td>${x.tf?`<span class="tf-badge">TF</span> ${esc(x.tf)}`:'未标注为 TF'}</td><td>${x.pcc66?.toFixed(6)??'NA'}</td><td>${x.pcc22?.toFixed(6)??'NA'}</td><td>${esc(x.description)}</td><td>${esc(x.go||'未注释')}</td></tr>`).join(''):'<tr><td colspan="7">没有符合当前条件的伙伴。</td></tr>';$('pageInfo').textContent=`第 ${page} / ${Math.max(1,Math.ceil(r.filtered/r.size))} 页 · 筛选后 ${r.filtered} / 全部 ${r.total}`;$('prev').disabled=page<=1;$('next').disabled=page*r.size>=r.filtered;document.querySelectorAll('[data-gene]').forEach(b=>b.onclick=guarded(()=>showGene(b.dataset.gene)));document.querySelectorAll('[data-heat]').forEach(b=>b.onclick=()=>addHeat(b.dataset.heat))}
function addHeat(id){const list=$('heatGenes').value.split(/[\s,，]+/).filter(Boolean);if(!list.includes(id))list.push(id);$('heatGenes').value=list.join(', ')}
async function geneData(id){if(!cache.has(id))cache.set(id,await api('gene',{gene:id}));return cache.get(id)}
async function showGene(id){const v=++detailEpoch;const d=await geneData(id);if(v!==detailEpoch)return;detail=d;$('detailTitle').textContent=d.alias?`${id} · ${d.alias}`:id;$('annotation').innerHTML=`${d.tf.length?'<span class="tf-badge">TF</span>':'<span class="note">未标注为 TF</span>'}<br><b>人工名称：</b>${esc(d.alias||'未标注')}<br><b>同源功能描述：</b>${esc(d.description)}<br><b>拟南芥对应信息：</b>${esc((d.homologs||[]).join('; ')||'未注释')}<br><b>TF 家族：</b>${esc(d.tf.join('; ')||'未注释')}<details><summary>GO 注释（${d.go.length}）</summary>${d.go.map(g=>`<div>${esc(g.id)} · ${esc(g.ontology)} · ${esc(g.description)} <small>(${esc(g.mapping)})</small></div>`).join('')||'未注释'}</details>${annotationEvidence(d)}<div class="source">来源：${d.sources.map(esc).join('<br>')||'无可验证注释'}</div>`;bars()}
function bars(){if(!detail)return;const reps=$('replicates').checked,max=Math.max(1,...detail.tissues.flatMap(t=>reps?t.replicates:[t.mean]));const color=barPalette.scale(0,max,'TPM');$('bars').innerHTML=detail.tissues.map(t=>`<div class="barrow" title="${esc(t.Tissue)} | ${esc(t.LargeGroup)} | 平均 ${t.mean.toFixed(6)} | 重复 ${t.replicates.join(', ')}"><span>${esc(t.Tissue.replace('ZL.',''))}</span><div class="bartrack"><div class="barfill" style="background:${color(t.mean)};width:${t.mean/max*100}%"></div>${reps?t.replicates.map(v=>`<i class="dot" style="left:calc(${v/max*100}% - 3px)"></i>`).join(''):''}</div><span class="barvalue">${t.mean.toFixed(2)}</span></div>`).join('')}
let netEpoch=0;
async function drawNetwork(){if(!current)return;const v=++netEpoch;$('networkInfo').textContent='读取网络…';const requested=netParams();const g=await api('network',requested);if(v!==netEpoch)return;graph=g;graphParams=requested;$('networkInfo').textContent=`全部一层命中 ${g.total}；绘制一层 ${g.firstShown}（省略 ${g.firstOmitted}）。当前 ${g.nodes.length} 节点 / ${g.edges.length} 边。${g.depth===2?`二层新候选 ${g.candidateCount}，因上限省略 ${g.secondOmitted}；仅扩展已绘制一层。`:''}`;$('tfNetworkInfo').textContent=`当前网络：${g.nodes.filter(n=>n.isTF).length} 个 TF / ${g.nodes.length} 个节点（含目标）`;$('activeType').textContent=current.geneType==='tf'?'当前查询：仅转录因子伙伴':'当前查询：全部基因伙伴';renderNetwork(g)}
let resetNetwork;
function renderNetwork(g){const svg=$('network'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();const group=document.createElementNS(ns,'g');svg.append(group);const positions=new Map();g.nodes.forEach((node,i)=>{const peers=g.nodes.filter(n=>n.level===node.level),j=peers.findIndex(n=>n.id===node.id),a=j/peers.length*Math.PI*2;positions.set(node.id,{x:node.level?400+(node.level===1?190:320)*Math.cos(a):400,y:node.level?260+(node.level===1?180:235)*Math.sin(a):260})});const lines=g.edges.map(e=>{const l=document.createElementNS(ns,'line');l.dataset.pcc=e.weight;const title=document.createElementNS(ns,'title');title.textContent=`${e.fromNode} ↔ ${e.toNode}: ${e.weight}`;l.append(title);group.append(l);return {l,e}});const elements=g.nodes.map(node=>{const el=document.createElementNS(ns,'g'),c=document.createElementNS(ns,node.isTF?'path':'circle'),t=document.createElementNS(ns,'text');const radius=node.level===0?14:8;c.classList.add('network-node');c.dataset.tf=String(node.isTF);if(node.isTF)c.setAttribute('d',`M 0 ${-radius*1.3} L ${radius*1.3} 0 L 0 ${radius*1.3} L ${-radius*1.3} 0 Z`);else c.setAttribute('r',String(radius));c.setAttribute('fill',['#ed843b','#167ca6','#8c6cc2'][node.level]);c.setAttribute('tabindex','0');c.setAttribute('role','button');c.setAttribute('aria-label',`${node.id} | ${node.isTF?'TF: '+node.tf.join('; '):'未标注为 TF'}`);const title=document.createElementNS(ns,'title');title.textContent=`${node.id}${node.alias?' · '+node.alias:''} | ${node.isTF?'TF: '+node.tf.join('; '):'未标注为 TF'}`;c.append(title);t.textContent=node.alias?`${node.alias} (${node.id})`:node.id;t.setAttribute('x','10');t.setAttribute('y','-9');if(node.level>0&&g.nodes.length>20)t.style.display='none';el.append(c,t);group.append(el);c.onfocus=()=>t.style.display='';c.onblur=()=>{if(node.level>0&&g.nodes.length>20)t.style.display='none'};el.onmouseenter=()=>t.style.display='';el.onmouseleave=()=>{if(node.level>0&&g.nodes.length>20)t.style.display='none'};c.onkeydown=guarded(e=>{if(e.key==='Enter')return showGene(node.id)});el.onpointerdown=e=>{e.stopPropagation();drag={id:node.id,startX:e.clientX,startY:e.clientY,moved:false};svg.setPointerCapture(e.pointerId)};return {el,node}});
let pan={x:0,y:0,s:1},drag;const point=e=>{const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse())};function update(){group.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${pan.s})`);lines.forEach(({l,e})=>{const a=positions.get(e.fromNode),b=positions.get(e.toNode);Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y}).forEach(([k,v])=>l.setAttribute(k,v))});elements.forEach(({el,node})=>{const p=positions.get(node.id);el.setAttribute('transform',`translate(${p.x} ${p.y})`)})}svg.onpointerdown=e=>{drag={p:point(e),x:pan.x,y:pan.y};svg.setPointerCapture(e.pointerId)};svg.onpointermove=e=>{if(!drag)return;const p=point(e);if(drag.id){if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>3)drag.moved=true;if(drag.moved)positions.set(drag.id,{x:(p.x-pan.x)/pan.s,y:(p.y-pan.y)/pan.s})}else{pan.x=drag.x+p.x-drag.p.x;pan.y=drag.y+p.y-drag.p.y}update()};svg.onpointerup=guarded(async()=>{const d=drag;drag=null;if(d?.id&&!d.moved)await showGene(d.id)});svg.onpointercancel=()=>drag=null;svg.onwheel=e=>{e.preventDefault();const p=point(e),s=Math.max(.3,Math.min(5,pan.s*Math.exp(-e.deltaY*.001)));pan.x=p.x-(p.x-pan.x)*s/pan.s;pan.y=p.y-(p.y-pan.y)*s/pan.s;pan.s=s;update()};resetNetwork=()=>{pan={x:0,y:0,s:1};update()};update();styleEdges()}
async function heat(){const ids=[...new Set($('heatGenes').value.split(/[\s,，]+/).filter(Boolean))];if(!ids.length||ids.length>30)throw Error('热图需 1–30 个基因');const data=await Promise.all(ids.map(geneData)),z=$('heatScale').value==='z';const vals=data.map(d=>{const v=d.tissues.map(t=>Math.log2(t.mean+1));if(!z)return v;const mean=v.reduce((a,b)=>a+b)/v.length,sd=Math.sqrt(v.reduce((a,b)=>a+(b-mean)**2,0)/(v.length-1));return v.map(x=>sd?(x-mean)/sd:0)}),max=z?Math.max(1,...vals.flat().map(Math.abs)):Math.max(1,...vals.flat());const colorFor=heatPalette.scale(z?-max:0,max,z?'Z-score':'log2(平均 TPM + 1)',z);$('heatInfo').textContent=`${ids.length} 基因 × 22 组织 · ${z?'对称色阶 ±':'色阶 0–'}${max.toFixed(2)}`;$('heatmap').innerHTML=`<table><thead><tr><th>基因 ID</th>${data[0].tissues.map(t=>`<th class="heathead"><span>${esc(t.Tissue.replace('ZL.',''))}</span></th>`).join('')}</tr></thead><tbody>${data.map((d,i)=>`<tr><td class="heatlabel">${esc(d.id)}</td>${vals[i].map((v,j)=>{const color=colorFor(v);return `<td class="heatcell" style="background:${color}" title="${esc(d.id)} | ${esc(d.tissues[j].Tissue)} | 平均 TPM ${d.tissues[j].mean.toFixed(6)} | 色值 ${v.toFixed(4)}"></td>`}).join('')}</tr>`).join('')}</tbody></table>`}
async function query(){if($('queryForm').dataset.busy)return;$('queryForm').dataset.busy='1';$('queryForm').querySelector('button').disabled=true;epoch++;netEpoch++;current={gene:$('gene').value.trim(),mode:$('mode').value,threshold:$('threshold').value,sign:$('sign').value,geneType:$('geneType').value};page=1;$('search').value='';$('status').className='';$('status').textContent='正在查询完整矩阵…';$('rows').replaceChildren();$('network').replaceChildren();$('count').textContent='';$('networkInfo').textContent='';try{await table();await Promise.all([drawNetwork(),showGene(current.gene)]);$('status').textContent=`${current.gene} · ${current.mode==='66'?'66 样本':'22 组织均值'} · 全部命中 ${result.total} 个伙伴（排除自身）`;$('heatGenes').value=[current.gene,...result.rows.slice(0,9).map(r=>r.id)].join(', ');await heat()}catch(e){current=null;$('detailTitle').textContent='基因详情';$('annotation').replaceChildren();$('bars').replaceChildren();$('heatmap').replaceChildren();throw e}finally{delete $('queryForm').dataset.busy;$('queryForm').querySelector('button').disabled=false}}
const barPalette=paletteControl('barPalette',bars),heatPalette=paletteControl('heatPalette',guarded(heat));
$('queryForm').onsubmit=guarded(e=>{e.preventDefault();return query()});$('redraw').onclick=guarded(drawNetwork);$('resetView').onclick=()=>resetNetwork?.();$('replicates').onchange=bars;$('addHeat').onclick=()=>detail&&addHeat(detail.id);$('renderHeat').onclick=guarded(heat);$('heatScale').onchange=guarded(heat);$('download').onclick=()=>download('partners');$('downloadEdges').onclick=()=>download('edges');$('downloadNetwork').onclick=()=>download('network');$('prev').onclick=guarded(()=>{page--;return table()});$('next').onclick=guarded(()=>{page++;return table()});for(const id of ['sort','order'])$(id).onchange=guarded(()=>{page=1;return table()});let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(guarded(()=>{page=1;return table()}),250)};
guarded(async()=>{const m=await api('meta');$('meta').textContent=`${m.genes.toLocaleString()} 个可查询基因 / ${m.inputGenes.toLocaleString()} 个输入基因`;await query()})();
for(const id of ['positiveColor','negativeColor','edgeWidth'])$(id).oninput=styleEdges;
