
let genes,ids,index,n,expression,annotations,hierarchy,samples,tissueIndices,vectors;
const rowCache=new Map();
export function initialize(meta,raw){
 ({genes,hierarchy,samples,tissueIndices}=meta);ids=genes.map(g=>g.Gene_ID);n=ids.length;index=new Map(ids.map((id,i)=>[id,i]));
 expression=new Map(meta.allIds.map((id,i)=>[id,raw.subarray(i*66,(i+1)*66)]));annotations=new Map(meta.annotations);
 vectors={'66':new Float64Array(n*66),'22':new Float64Array(n*22)};
 for(let i=0;i<n;i++){const values=expression.get(ids[i]);
  for(const mode of ['66','22']){const k=Number(mode),v=mode==='66'?Array.from(values,x=>Math.log2(x+1)):tissueIndices.map(t=>Math.log2(t.reduce((s,j)=>s+values[j],0)/3+1));
   const mean=v.reduce((s,x)=>s+x,0)/k,norm=Math.sqrt(v.reduce((s,x)=>s+(x-mean)**2,0));
   for(let j=0;j<k;j++)vectors[mode][i*k+j]=norm?(v[j]-mean)/norm:NaN;
  }
 }
 rowCache.clear();
}
export function correlationRow(i,mode){return row(i,mode).values}
function row(i,mode){
 const key=mode+':'+i;if(rowCache.has(key))return rowCache.get(key);
 const k=Number(mode),v=vectors[mode],a=i*k,values=new Float32Array(n);
 for(let j=0;j<n;j++){let dot=0;const b=j*k;for(let c=0;c<k;c++)dot+=v[a+c]*v[b+c];values[j]=Math.min(1,Math.max(-1,dot));}
 const r={values,readFloatLE:offset=>values[offset/4]};if(rowCache.size>=96)rowCache.delete(rowCache.keys().next().value);rowCache.set(key,r);return r;
}
function validateGene(id,mode){if(!index.has(id))throw Error(expression.has(id)?'该基因未通过表达筛选（至少一个组织平均 TPM > 1）。':'无效或未知基因 ID。');if(genes[index.get(id)][`PCC${mode}_defined`]!=='TRUE')throw Error('该基因在当前模式下为零方差，PCC 未定义。')}
function params(u){const get=(k,d)=>u.searchParams.get(k)??d;const gene=get('gene','').trim(),mode=get('mode','66'),sign=get('sign','positive'),threshold=Number(get('threshold','0.8'));if(!['66','22'].includes(mode)||!['positive','negative','both'].includes(sign)||!Number.isFinite(threshold)||threshold<0||threshold>1||get('threshold','0.8').trim()==='')throw Error('参数错误：模式 66/22，阈值须为 0–1。');validateGene(gene,mode);const geneType=get('geneType','all');if(!['all','tf'].includes(geneType))throw Error('无效的基因类型');return {gene,mode,sign,threshold,geneType}}
const isTF=id=>(annotations.get(id)?.tf||[]).length>0;
const matches=(v,p)=>Number.isFinite(v)&&(p.sign==='positive'?v>=p.threshold:p.sign==='negative'?v<=-p.threshold:Math.abs(v)>=p.threshold);
function partners(p){const i=index.get(p.gene),b=row(i,p.mode),b66=p.mode==='66'?b:row(i,'66'),b22=p.mode==='22'?b:row(i,'22');const result=[];for(let j=0;j<n;j++){const v=b.readFloatLE(j*4);if(j!==i&&matches(v,p)&&(p.geneType!=='tf'||isTF(ids[j]))){const a=annotations.get(ids[j]);result.push({id:ids[j],pcc:v,pcc66:b66.readFloatLE(j*4),pcc22:b22.readFloatLE(j*4),description:a.description,alias:a.alias,homologs:(a.homologs||[]).join('; '),annotationSource:a.sources.join('; '),annotationEvidence:JSON.stringify(a.evidence||[]),tf:a.tf.join(';'),go:a.go.map(g=>`${g.id} ${g.description}`).join('; ')})}}return result.sort((a,b)=>Math.abs(b.pcc)-Math.abs(a.pcc)||a.id.localeCompare(b.id))}
function int(u,k,d,min,max){const x=Number(u.searchParams.get(k)??d);if(!Number.isInteger(x)||x<min||x>max)throw Error(`${k} 须为 ${min}–${max} 的整数`);return x}
function network(p,u){const limit=int(u,'limit',50,1,200),depth=int(u,'depth',1,1,2),cap=int(u,'cap',150,2,300),all=partners(p),first=all.slice(0,Math.min(limit,cap-1));const nodes=new Map([[p.gene,0],...first.map(r=>[r.id,1])]);const edges=[],seen=new Set();let candidateCount=0,omitted=0;const add=(a,b,w)=>{const key=[a,b].sort().join('|');if(!seen.has(key)){seen.add(key);edges.push({fromNode:a,toNode:b,weight:w,direction:'undirected',fromAltName:annotations.get(a).alias,toAltName:annotations.get(b).alias})}};first.forEach(r=>add(p.gene,r.id,r.pcc));if(depth===2){const candidates=new Map();for(const seed of first){const b=row(index.get(seed.id),p.mode);for(let j=0;j<n;j++){const v=b.readFloatLE(j*4);if(ids[j]!==seed.id&&matches(v,p)&&!nodes.has(ids[j])&&(p.geneType!=='tf'||isTF(ids[j]))){const old=candidates.get(ids[j]);if(!old||Math.abs(v)>Math.abs(old.weight))candidates.set(ids[j],{fromNode:seed.id,toNode:ids[j],weight:v})}}}candidateCount=candidates.size;const ranked=[...candidates.values()].sort((a,b)=>Math.abs(b.weight)-Math.abs(a.weight)||a.toNode.localeCompare(b.toNode));const selected=ranked.slice(0,cap-nodes.size);selected.forEach(e=>{nodes.set(e.toNode,2);add(e.fromNode,e.toNode,e.weight)});omitted=ranked.length-selected.length}
if(u.searchParams.get('inter')==='true'){const list=[...nodes.keys()].filter(id=>id!==p.gene);for(let i=0;i<list.length;i++){const b=row(index.get(list[i]),p.mode);for(let j=i+1;j<list.length;j++){const v=b.readFloatLE(index.get(list[j])*4);if(matches(v,p))add(list[i],list[j],v)}}}
return {nodes:[...nodes].map(([id,level])=>({id,level,alias:annotations.get(id)?.alias||'',tf:annotations.get(id)?.tf||[],isTF:isTF(id)})),edges,total:all.length,firstShown:first.length,firstOmitted:all.length-first.length,candidateCount,secondOmitted:omitted,depth,cap,limit}}
const tsv=(rows,columns)=>'\uFEFF'+[columns.join('\t'),...rows.map(r=>columns.map(c=>String(r[c]??'').replace(/[\t\r\n]/g,' ')).join('\t'))].join('\n');

export function request(route,p={}){const u=new URL('/api/'+route,'https://local.invalid');u.search=new URLSearchParams(p);let data;if(u.pathname==='/api/meta')data={genes:n,inputGenes:expression.size,tissues:hierarchy,samples};else if(u.pathname==='/api/gene'){const id=u.searchParams.get('gene');if(!expression.has(id))throw Error('未知基因 ID');const values=expression.get(id);data={...(annotations.get(id)||{id,description:'未注释',go:[],tf:[],sources:[]}),tissues:hierarchy.map((t,i)=>({...t,replicates:tissueIndices[i].map(j=>values[j]),mean:tissueIndices[i].reduce((s,j)=>s+values[j],0)/3}))}}else if(u.pathname==='/api/query'){const p=params(u),all=partners(p),search=(u.searchParams.get('search')||'').toLowerCase(),sort=u.searchParams.get('sort')||'absolute',order=u.searchParams.get('order')||'desc';if(!['absolute','pcc','id','description'].includes(sort)||!['asc','desc'].includes(order))throw Error('排序参数错误');let filtered=all.filter(r=>[r.id,r.alias,r.description,r.homologs,r.tf,r.go,r.annotationEvidence].join(' ').toLowerCase().includes(search));filtered.sort((a,b)=>{const v=sort==='absolute'?Math.abs(a.pcc)-Math.abs(b.pcc):sort==='pcc'?a.pcc-b.pcc:String(a[sort]).localeCompare(String(b[sort]));return (order==='asc'?v:-v)||a.id.localeCompare(b.id)});const page=int(u,'page',1,1,100000),size=int(u,'size',25,1,100);data={...p,total:all.length,filtered:filtered.length,page,size,rows:filtered.slice((page-1)*size,page*size)}}else if(u.pathname==='/api/network')data=network(params(u),u);else if(u.pathname==='/api/download'){const p=params(u),format=u.searchParams.get('format')||'partners';let rows,cols;if(format==='network'){rows=network(p,u).edges;cols=['fromNode','toNode','weight','direction','fromAltName','toAltName']}else if(format==='edges'){rows=partners(p).map(r=>({fromNode:p.gene,toNode:r.id,weight:r.pcc,direction:'undirected',fromAltName:annotations.get(p.gene).alias,toAltName:r.alias}));cols=['fromNode','toNode','weight','direction','fromAltName','toAltName']}else if(format==='partners'){rows=partners(p);cols=['id','alias','pcc','pcc66','pcc22','description','homologs','tf','go','annotationSource','annotationEvidence']}else throw Error('下载格式错误');return {text:tsv(rows,cols),filename:`${p.gene}_${p.mode}_${p.sign}_${format}.tsv`}}else throw Error('Unknown route');return data;}
